---

- hosts: 127.0.0.1
  connection: local
  gather_facts: no
  sudo: no
  tasks:
    - name: test marathon
      marathon_app:
        state: present
        name: docker-registry
        host: http://10.10.7.10:8080
        memory: 128.0
        instances: 1
        container:
          type: DOCKER
          docker:
            image: registry:0.8.1
            network: BRIDGE
            portMappings:
              - { containerPort: 5000, hostPort: 0, protocol: "tcp" }
        env:
          SETTINGS_FLAVOR: local
          SEARCH_BACKEND: sqlalchemy
      register: marathon

    - debug: var=marathon
