---

- name: prevent mesos slave process from starting
  template: src=mesos-slave.override.j2 dest=/etc/init/mesos-slave.override
  notify:
  - restart zookeeper
  - restart master

- name: configure ip that mesos master will listen on
  template: src=ip.j2 dest=/etc/mesos-master/ip
  notify:
  - restart zookeeper
  - restart master
